# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47a2f49ae8e7888eb3d6a0ffbf32cce16f0811d454f0292001f7f6772fcd9a869525b6e71547359205fbb6265e94251e22dcc98179c8a6b78042c033d517295a

test:
  secret_key_base: 559dd86038cd7c582518d0e664481fb4466726127dda962a783025a9766863eaf0c7d36f2b55c60b2843a722a9414725f6f61c13f5364bffbe1adbd94cfcb208

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
